#include <Arduino.h>
#include <Audio.h>
#include <arm_math.h>
#include <SPI.h>
#include <SD.h>

#define FFT_SIZE      1024
#define RECORD_WINDOWS 25
#define SAMPLE_RATE   AUDIO_SAMPLE_RATE_EXACT
#define SD_CS_PIN     BUILTIN_SDCARD   // or 10 if using external SD module

AudioInputI2S            i2sIn;
AudioAnalyzeFFT1024      fft;
AudioConnection          patchCord1(i2sIn, 0, fft, 0);
AudioControlSGTL5000     sgtl5000_1;   // For Teensy Audio shield (ignore if using raw I2S mic)

float avgMag[FFT_SIZE/2];
File templateFile;

void setup() {
  Serial.begin(115200);
  delay(1000);
  Serial.println("=== Gunshot Template Recorder ===");

  AudioMemory(20);
  sgtl5000_1.enable();
  sgtl5000_1.inputSelect(AUDIO_INPUT_LINEIN);
  sgtl5000_1.volume(0.8);

  if (!SD.begin(SD_CS_PIN)) {
    Serial.println("SD initialization failed!");
    while (1);
  }
  Serial.println("SD initialized successfully.");

  fft.windowFunction(AudioWindowHanning1024);
  memset(avgMag, 0, sizeof(avgMag));
  
  Serial.println("Recording sound templates...");
  recordTemplates();
  saveTemplateToSD();
  Serial.println("✅ Template saved to SD successfully!");
}

void loop() {
  // Nothing here
}

void recordTemplates() {
  int windowCount = 0;

  while (windowCount < RECORD_WINDOWS) {
    if (fft.available()) {
      for (int i = 0; i < FFT_SIZE / 2; i++) {
        float mag = fft.read(i);
        avgMag[i] += mag;
      }
      windowCount++;
      Serial.print(".");
    }
  }

  // Average across all windows
  for (int i = 0; i < FFT_SIZE / 2; i++) {
    avgMag[i] /= RECORD_WINDOWS;
  }

  Serial.println("\nTemplate recording done!");
}

void saveTemplateToSD() {
  templateFile = SD.open("/gun_template_mag.h", FILE_WRITE);
  if (!templateFile) {
    Serial.println("Failed to open file for writing!");
    return;
  }

  templateFile.println("// Auto-generated gunshot template magnitude array");
  templateFile.println("// Generated by Record_Template_To_SD.ino");
  templateFile.print("const float gun_template_mag[");
  templateFile.print(FFT_SIZE/2);
  templateFile.println("] = {");

  for (int i = 0; i < FFT_SIZE/2; i++) {
    templateFile.print(avgMag[i], 6);
    if (i < FFT_SIZE/2 - 1) templateFile.print(", ");
    if ((i + 1) % 8 == 0) templateFile.println();
  }

  templateFile.println("};");
  templateFile.close();
  Serial.println("Template file written as gun_template_mag.h");
}
